### ISSUE TITLE
What is defer?

### ISSUE THREAD

**Issue by Goldenboy3023** [onthegocode/lottie#5]
### Discussed in https://github.com/onthegocode/lottie/discussions/4

<div type='discussions-op-text'>

<sup>Originally posted by **Goldenboy3023** October  2, 2022</sup>
What is the defer you put in my project but not on this one?</div>

**Comment by onthegocode** [comment]
Defer tells JavaScript to basically load after everything else has been loaded.

**Comment by Goldenboy3023** [comment]
> Defer tells JavaScript to basically load after everything else has been loaded.
